security:
    encoders:
        AppBundle\Entity\Usuario:
            algorithm: md5
            encode_as_base64: false
            iterations: 0
 
    providers:
        user_provider:
            entity:
                class: AppBundle:Usuario
                property: usuario
 
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
 
        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
            logout:
                path: /logout
                target: /login
 
    access_control:
        - { path: ^/registro, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }
