security:
    encoders:
        App\Entity\Usuario:
            algorithm: bcrypt
            cost: 11
            encode_as_base64: false
            iterations: 0
 
    providers:
        user_provider:
            entity:
                class: App\Entity\Usuario
                #                property: usuario
 
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
 
        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                provider: user_provider
                default_target_path: /offer/listAll
                always_use_default_target_path: true
            logout:
                path: /logout
                target: /login
 
    access_control:
        - { path: ^/registro, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/, roles: ROLE_USER, requires_channel: https }
